/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrecioMP;

import MateriaPrima.MateriaPirmaGUI;
import Modelos.PrecioMP;
import Modelos.Usuarios;
import Servicios.Conexion;
import Servicios.PrecioMP_servicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PrecioMPGUI extends javax.swing.JFrame {
    private final PrecioMP_servicio precioMP_servicio = new PrecioMP_servicio();
    private List<PrecioMP> precio;
    
    private final toExcel excel=new toExcel();
    Usuarios mod;
  
    public PrecioMPGUI() {
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(0);
        this.PrecioMPGUI();  
        
        //Boton Exportar Precio MP
        btnExportarExcel.setFocusPainted(false);
        btnExportarExcel.setBorderPainted(false);
        //jButton4.setContentAreaFilled(false);
        
        //Boton Regresar
        btnRegresarPrecioMP.setFocusPainted(false);
        btnRegresarPrecioMP.setBorderPainted(false);
        btnRegresarPrecioMP.setContentAreaFilled(false);
    }
    public PrecioMPGUI(Usuarios mod){
        initComponents();
        this.mod = mod;
        this.setResizable(false);
        this.setDefaultCloseOperation(0);
        this.PrecioMPGUI();
        
        //Boton Exportar Precio MP
        btnExportarExcel.setFocusPainted(false);
        btnExportarExcel.setBorderPainted(false);
        //jButton4.setContentAreaFilled(false);
        
        //Boton Regresar
        btnRegresarPrecioMP.setFocusPainted(false);
        btnRegresarPrecioMP.setBorderPainted(false);
        btnRegresarPrecioMP.setContentAreaFilled(false);
        
        if(mod.getId_tipo()== 4){
            btnModificarPrecioMP.setEnabled(true);
            btnAgregarPrecioMP.setEnabled(true);           
        }  
    } 
     
    private void PrecioMPGUI() {
        try{
            this.precio = this.precioMP_servicio.recuperarTodas(Conexion.obtener());
            DefaultTableModel dtm = (DefaultTableModel) tblPrecioMP.getModel();
            dtm.setRowCount(0);
            for(int i = 0; i < this.precio.size(); i++){
                dtm.addRow(new Object[]{
                    this.precio.get(i).getCalibre(),
                    this.precio.get(i).getPesoUnitario(),
                    this.precio.get(i).getMoneda()
                });  
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
        }catch(ClassNotFoundException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
        }
     
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
              getImage(ClassLoader.getSystemResource("jc/img/jc.png"));

        return retValue;
    }

    /**to
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecioMP = new javax.swing.JLabel();
        btnAgregarPrecioMP = new javax.swing.JButton();
        btnModificarPrecioMP = new javax.swing.JButton();
        btnRegresarPrecioMP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrecioMP = new javax.swing.JTable();
        btnExportarExcel = new javax.swing.JButton();
        lblExportar = new javax.swing.JLabel();
        lblJCIcono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecioMP.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        lblPrecioMP.setText("PRECIO M. P.");
        getContentPane().add(lblPrecioMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 370, 50));

        btnAgregarPrecioMP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarPrecioMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/1004733.png"))); // NOI18N
        btnAgregarPrecioMP.setText("Agregar");
        btnAgregarPrecioMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPrecioMPActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPrecioMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        btnModificarPrecioMP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificarPrecioMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/modificar.png"))); // NOI18N
        btnModificarPrecioMP.setText("Modificar");
        btnModificarPrecioMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPrecioMPActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarPrecioMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 30));

        btnRegresarPrecioMP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegresarPrecioMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/boton_regresar.png"))); // NOI18N
        btnRegresarPrecioMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPrecioMPActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarPrecioMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 120, 50));

        tblPrecioMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CALIBRE", "P. U. (KG)", "MONEDA"
            }
        ));
        jScrollPane2.setViewportView(tblPrecioMP);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 540, 370));

        btnExportarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/excel.png"))); // NOI18N
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 60, 60));

        lblExportar.setText("EXPORTAR");
        getContentPane().add(lblExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        lblJCIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jc/img/jcLogo.png"))); // NOI18N
        getContentPane().add(lblJCIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(135, 206, 235));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPrecioMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPrecioMPActionPerformed
        int fila_seleccionada = tblPrecioMP.getSelectedRow();
         
        if(fila_seleccionada >= 0){
            PrecioMPGUI.this.dispose();
            ModificarPrecioMP modificar = new ModificarPrecioMP(this.precio.get(fila_seleccionada),mod);
            modificar.setVisible(true);
            modificar.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione una fila.");
        }           
    }//GEN-LAST:event_btnModificarPrecioMPActionPerformed

           
    private void btnRegresarPrecioMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPrecioMPActionPerformed
      
        try {
            MateriaPirmaGUI mn= new MateriaPirmaGUI(mod);
            mn.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(PrecioMPGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrecioMPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRegresarPrecioMPActionPerformed

    private void btnAgregarPrecioMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPrecioMPActionPerformed
        PrecioMPGUI.this.dispose();
        AgregarPrecioMP vista = new AgregarPrecioMP(mod);
        vista.setVisible(true);
        vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarPrecioMPActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        excel.WriteExcelPrecioMP();
        JOptionPane.showMessageDialog(this, "Datos Exportados.");
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrecioMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrecioMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrecioMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrecioMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrecioMPGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPrecioMP;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnModificarPrecioMP;
    private javax.swing.JButton btnRegresarPrecioMP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExportar;
    private javax.swing.JLabel lblJCIcono;
    private javax.swing.JLabel lblPrecioMP;
    private javax.swing.JTable tblPrecioMP;
    // End of variables declaration//GEN-END:variables

}